name: Convert Icon Pack

on:
  workflow_dispatch:
    inputs:
      zip_file_url:
        description: 'URL of the zipped icon pack'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Download Zip File
        run: |
          curl -L ${{ github.event.inputs.zip_file_url }} -o images.zip

      - name: Create Images Directory
        run: mkdir images

      - name: Extract Zip File to Images Directory
        run: unzip images.zip -d images

      - name: Run Python Script
        run: python main.py images

      - name: Archive Output
        uses: actions/upload-artifact@v4
        with:
          name: converted-iconpack
          path: images
